### PR TITLE
Updated mods and unified materials

### PR DESCRIPTION
**Pull request by austragus**
MultiMC test instance:
https://www.dropbox.com/s/7ju2ez5qe079kzo/NBTorqued%20Testpack2.zip?dl=0

New mods:
- Base Metals
- ConnectedTextureMod
- ForgeMultipart
- MMD Orespawn
- NotEnoughIDs
- Rockhounding Core
- Rockhounding Chemistry
- StuffASockInIt
- Tesla API
- UniDict
- WanionLib

Removed mods:
- ATM Rockhounding, functionality moved to Rockhounding Core and Chemistry
- Avaritia Additions, functionality moved to Avaritia
- Dynamic Surroundings, can't remember why this isn't in; will include it in later versions
- Enchiridion, was causing errors; will fix later
- TombManyGraves, was causing problems; replaced by Gravestones

### CODE REVIEW

**Comment by Saereth** [comment]
orespawn was causing major worldgen issues iwth cofh in the end, have you verified this is corrected?

**Comment by austragus** [comment]
Most of the ore generation done by orespawn has been disabled in the config files. I have also done a fair bit of mining using rftools builder blocks in all three biomes and have not found anything weird aside from the ugly end metal textures.

I cannot for the life of me remember why I added Tesla. Pack works without it. I'll promptly update.

TombManyGraves was occasionally causing a crash on loading into/teleporting between dimensions. I'll see what I can do to get it back.

**Comment by Saereth** [comment]
the orespawn issue specifically was causing all overworld ores to spawn in the end even with all the orespawn ores disabled, still curious about the tungstensteel issue, that being my biggest concern as that would hugely impact balance with it just being removed

**Comment by austragus** [comment]
Ah yes, you've told me about these issues. I could not find any ores in the end that aren't listed in the cofh json configs. As for the removal of tungsteel, I simply changed the recipe of Pewter, a relatively unused decorative metal from Rockhounding to that of the old tungsteel.

**Comment by Saereth** [comment]
that could work, or I could add tungstensteel to bbtweaks, I'm gonna merge in these to my local environment and make sure everything looks right, thanks for all your help on this!

**Comment by austragus** [comment]
No problems! Happy to help.

**Pull request closed without merging**
